name: Pipeline de CI/CD

on:
  push:
    branches:
      - main
    tags:
      - '*'
permissions:
  id-token: write
  contents: read
  
jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3
# *************************************************************************** 
     #configurando AWS   
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::288786226667:role/ecr-role
          aws-region: us-east-1

      #login  ECR    
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
# *************************************************************************** 

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install httpx

      - name: Executar testes
        run: |
          pytest

  build-push:
    needs: teste
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Fazer login no DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Capturar a tag do commit ou nome do branch
        id: tag
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            SAFE_BRANCH_NAME=${BRANCH_NAME//\//-}
            echo "GIT_TAG=${SAFE_BRANCH_NAME}" >> $GITHUB_ENV
          fi

      - name: Construir imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/minha-aplicacao-fastapi:${{ env.GIT_TAG }} .

      - name: Enviar imagem Docker
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/minha-aplicacao-fastapi:${{ env.GIT_TAG }}