name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testes_unitarios:
    runs-on: ubuntu-latest

    steps:
    - name: Fazer Checkout do Código
      uses: actions/checkout@v2
      
    - name: Configurando o Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Instalando as Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Rodando os Testes
      run: |
        pytest