name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testes_unitarios:
    runs-on: ubuntu-latest

    steps:
    - name: Fazer Checkout do Código
      uses: actions/checkout@v2
      
    - name: Configurando o Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Instalando as Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Rodando os Testes
      run: |
        pytest

  deploy:
    needs: testes_unitarios
    runs-on: ubuntu-latest

    steps:
    - name: Fazer Checkout do Código
      uses: actions/checkout@v2

    - name: Configurar AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Atualize a região conforme necessário

    - name: Instalar EB CLI
      run: |
        pip install awsebcli

    - name: Inicializar Elastic Beanstalk
      run: |
        eb init -p python-3.7 my-app --region us-east-1  # Atualize o nome do aplicativo e a região conforme necessário

    - name: Terminar Ambiente Elastic Beanstalk se Existir
      run: |
        eb terminate my-app-env --force || echo "Environment does not exist or has already been terminated"

    - name: Criar Ambiente Elastic Beanstalk
      run: |
        eb create my-app-env  # Atualize o nome do ambiente conforme necessário

    - name: Fazer Deploy para Elastic Beanstalk
      run: |
        eb deploy

    - name: Obter Status do Elastic Beanstalk
      run: |
        eb status